a=set()
number=int(input("Enter the number: "))
a.add(number)
number=int(input("Enter the number: "))
a.add(number)
number=int(input("Enter the number: "))
a.add(number)
number=int(input("Enter the number: "))
a.add(number)
number=int(input("Enter the number: "))
a.add(number)
number=int(input("Enter the number: "))
a.add(number)
number=int(input("Enter the number: "))
a.add(number)
number=int(input("Enter the number: "))
a.add(number)
print(type(a))
print(a)
