d={}
keys=input("enter the name: ")
values=input("enter the language: ")
d.update({keys:values})
keys=input("enter the name: ")
values=input("enter the language: ")
d.update({keys:values})
keys=input("enter the name: ")
values=input("enter the language: ")
d.update({keys:values})
keys=input("enter the name: ")
values=input("enter the language: ")
d.update({keys:values})
# print(d.items())
print(d)
