fruits=[]
a=input("Enter the fruits name: ")
b=input("Enter the fruits name: ")
c=input("Enter the fruits name: ")
d=input("Enter the fruits name: ")
e=input("Enter the fruits name: ")
f=input("Enter the fruits name: ")
g=input("Enter the fruits name: ")
fruits.append(a)
fruits.append(b)
fruits.append(c)
fruits.append(d)
fruits.append(e)
fruits.append(f)
fruits.append(g)
print(fruits)