Students_marks=[]
a=int(input("Enter the Student_marks: "))
b=int(input("Enter the Student_marks: "))
c=int(input("Enter the Student_marks: "))
d=int(input("Enter the Student_marks: "))
e=int(input("Enter the Student_marks: "))
f=int(input("Enter the Student_marks: "))
g=int(input("Enter the Student_marks: "))
Students_marks.append(a)
Students_marks.append(b)
Students_marks.append(c)
Students_marks.append(d)
Students_marks.append(e)
Students_marks.append(f)
Students_marks.append(g)
Students_marks.sort()
print(Students_marks)